### ISSUE TITLE
Fdp Crash

### ISSUE THREAD

**Issue by anbuchicken** [UnlegitMC/FDPClient#1203]
![Minecraft Launcher 3_6_2022 7_01_26 AM](https://user-images.githubusercontent.com/101047041/156922185-bf64a474-e857-4d35-b115-36fc59bf7fb5.png) Idk why it crash btw I have no jvm argument

**Comment by LukeIsHereToDevelop** [comment]
I get the same error. I even tried reinstalling FDPClient but nothing changes.

**Comment by anbuchicken** [comment]
Same I tried reinstaling it

**Comment by HowardZHY** [comment]
log?

**Comment by anbuchicken** [comment]
Idk how to get logs sorry

**Comment by HowardZHY** [comment]
/.minecraft/logs/latest.log and debug.log



At 2022-03-07 00:39:19, "anbuchicken" ***@***.***> wrote:

Idk how to get logs sorry

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by F3D7P6hxg** [comment]
use another launcher like gdlauncher

**Comment by 3000IQPlay** [comment]
Can

> ![Minecraft Launcher 3_6_2022 7_01_26 AM](https://user-images.githubusercontent.com/101047041/156922185-bf64a474-e857-4d35-b115-36fc59bf7fb5.png) Idk why it crash btw I have no jvm argument

Can't be fixed without crash log

**Comment by LukeIsHereToDevelop** [comment]
I get this error:
```[15:41:11]` [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:41:11] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:41:11] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[15:41:11] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\User\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\jre-legacy\windows-x64\jre-legacy
[15:41:11] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from FDPClient-69a0660.jar
[15:41:11] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.9_HD_U_M5.jar
[15:41:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:41:11] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:41:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/mods/FDPClient-69a0660.jar Service=LaunchWrapper Env=CLIENT
[15:41:11] [main/DEBUG]: Instantiating coremod class TransformerLoader
[15:41:11] [main/DEBUG]: The coremod net.ccbluex.liquidbounce.injection.forge.TransformerLoader requested minecraft version 1.8.9 and minecraft is 1.8.9. It will be loaded.
[15:41:11] [main/INFO]: Compatibility level set to JAVA_8
[15:41:11] [main/DEBUG]: Enqueued coremod TransformerLoader
[15:41:11] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:41:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:41:11] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[15:41:11] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[15:41:11] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[15:41:11] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[15:41:11] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\User\AppData\Roaming\.minecraft\mods\OptiFine_1.8.9_HD_U_M5.jar
[15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:41:11] [main/DEBUG]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[15:41:11] [main/DEBUG]: Injection complete
[15:41:11] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin}
[15:41:11] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[15:41:12] [main/DEBUG]: Read 825 binary patches
[15:41:12] [main/DEBUG]: Loading deobfuscation resource /deobfuscation_data-1.8.9.lzma with 27891 records
[15:41:12] [main/WARN]: Problem loading class
java.lang.SecurityException: SHA-256 digest error for aqp$g.class
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:218) ~[?:1.8.0_51]
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:241) ~[?:1.8.0_51]
	at java.util.jar.JarVerifier.update(JarVerifier.java:228) ~[?:1.8.0_51]
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:479) ~[?:1.8.0_51]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.readFully(LaunchClassLoader.java:301) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.getClassBytes(LaunchClassLoader.java:373) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:57) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:210) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:184) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:153) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:182) [FMLSanityChecker.class:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:156) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:41:12] [main/ERROR]: Patcher expecting non-empty class data file for net.minecraft.world.gen.structure.StructureStrongholdPieces$PortalRoom, but received empty.
[15:41:12] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.world.gen.structure.StructureStrongholdPieces$PortalRoom, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:161) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.world.gen.structure.StructureStrongholdPieces$PortalRoom, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:95) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:58) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:210) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:184) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:153) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:182) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:156) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?]
	... 2 more
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)```

**Comment by F3D7P6hxg** [comment]
try another launcher like gdlauncher or tlauncher

**Comment by HowardZHY** [comment]
vanilla jar may be corrupt



At 2022-03-08 18:49:43, "Luca" ***@***.***> wrote:

I get this error:
[15:41:11]` [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker [15:41:11] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker [15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker [15:41:11] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading [15:41:11] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\User\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\jre-legacy\windows-x64\jre-legacy [15:41:11] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from FDPClient-69a0660.jar [15:41:11] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.9_HD_U_M5.jar [15:41:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker [15:41:11] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker [15:41:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/mods/FDPClient-69a0660.jar Service=LaunchWrapper Env=CLIENT [15:41:11] [main/DEBUG]: Instantiating coremod class TransformerLoader [15:41:11] [main/DEBUG]: The coremod net.ccbluex.liquidbounce.injection.forge.TransformerLoader requested minecraft version 1.8.9 and minecraft is 1.8.9. It will be loaded. [15:41:11] [main/INFO]: Compatibility level set to JAVA_8 [15:41:11] [main/DEBUG]: Enqueued coremod TransformerLoader [15:41:11] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker [15:41:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker [15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker [15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker [15:41:11] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker [15:41:11] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions [15:41:11] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader [15:41:11] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer [15:41:11] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\User\AppData\Roaming\.minecraft\mods\OptiFine_1.8.9_HD_U_M5.jar [15:41:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper [15:41:11] [main/DEBUG]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers [15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer [15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer [15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer [15:41:11] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer [15:41:11] [main/DEBUG]: Injection complete [15:41:11] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} [15:41:11] [main/DEBUG]: Running coremod plugin FMLCorePlugin [15:41:12] [main/DEBUG]: Read 825 binary patches [15:41:12] [main/DEBUG]: Loading deobfuscation resource /deobfuscation_data-1.8.9.lzma with 27891 records [15:41:12] [main/WARN]: Problem loading class java.lang.SecurityException: SHA-256 digest error for aqp$g.class at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:218) ~[?:1.8.0_51] at java.util.jar.JarVerifier.processEntry(JarVerifier.java:241) ~[?:1.8.0_51] at java.util.jar.JarVerifier.update(JarVerifier.java:228) ~[?:1.8.0_51] at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:479) ~[?:1.8.0_51] at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:1.8.0_51] at net.minecraft.launchwrapper.LaunchClassLoader.readFully(LaunchClassLoader.java:301) [launchwrapper-1.12.jar:?] at net.minecraft.launchwrapper.LaunchClassLoader.getClassBytes(LaunchClassLoader.java:373) [launchwrapper-1.12.jar:?] at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:57) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:210) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:184) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:153) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:182) [FMLSanityChecker.class:?] at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:156) [forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?] at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] [15:41:12] [main/ERROR]: Patcher expecting non-empty class data file for net.minecraft.world.gen.structure.StructureStrongholdPieces$PortalRoom, but received empty. [15:41:12] [main/ERROR]: Unable to launch java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.world.gen.structure.StructureStrongholdPieces$PortalRoom, but received empty, your vanilla jar may be corrupt. at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:161) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?] at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.world.gen.structure.StructureStrongholdPieces$PortalRoom, but received empty, your vanilla jar may be corrupt. at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:95) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:58) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:210) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:184) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:153) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:182) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:156) ~[forge-1.8.9-11.15.1.2318-1.8.9.jar:?] ... 2 more [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30) [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.SecurityManager.checkExit(SecurityManager.java:761) [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Runtime.exit(Runtime.java:107) [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.System.exit(System.java:971) [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:138) [15:41:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
