### ISSUE TITLE
[Bug] FDPClient crashes (git-85a6126)

### ISSUE THREAD

**Issue by FDPUser443** [UnlegitMC/FDPClient#1573]
Time: 24.03.22 16:45
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.ccbluex.liquidbounce.LiquidBounce.initClient(LiquidBounce.kt:123)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3196)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Can't find language file! Try sync gitsubmodule if this is a custom build!
	at net.ccbluex.liquidbounce.ui.i18n.Language.find(Language.kt:34)
	at net.ccbluex.liquidbounce.ui.i18n.Language.read(Language.kt:40)
	at net.ccbluex.liquidbounce.ui.i18n.Language.<init>(Language.kt:12)
	at net.ccbluex.liquidbounce.ui.i18n.LanguageManager.<clinit>(LanguageManager.kt:11)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ccbluex.liquidbounce.LiquidBounce.initClient(LiquidBounce.kt:123)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3196)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by HowardZHY** [comment]
u'd better upload latest.log y fml-client log en logs folder
