### ISSUE TITLE
[Bug] <Pojavlancher Crashes>

### ISSUE THREAD

**Issue by SMAAMX** [UnlegitMC/FDPClient#1727]
**Describe the bug**
<Pojavlancher Crashes.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Start 1.8.9
2. Loading Screen...
3. Crashed

**Crash Report**

---- Minecraft Crash Report ----

Time: 3/25/22 8:57 AM
Description: Rendering screen

kotlin.UninitializedPropertyAccessException: lateinit property scriptManager has not been initialized
	at net.ccbluex.liquidbounce.LiquidBounce.getScriptManager(LiquidBounce.kt:49)
	at net.ccbluex.liquidbounce.ui.client.GuiScripts$GuiList.func_148127_b(GuiScripts.kt:180)
	at net.minecraft.client.gui.GuiSlot.func_148138_e(GuiSlot.java:123)
	at net.minecraft.client.gui.GuiSlot.func_148135_f(GuiSlot.java:177)
	at net.minecraft.client.gui.GuiSlot.func_148121_k(GuiSlot.java:172)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:694)
	at net.ccbluex.liquidbounce.ui.client.GuiScripts.func_73863_a(GuiScripts.kt:49)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1431)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ccbluex.liquidbounce.LiquidBounce.getScriptManager(LiquidBounce.kt:49)
	at net.ccbluex.liquidbounce.ui.client.GuiScripts$GuiList.func_148127_b(GuiScripts.kt:180)
	at net.minecraft.client.gui.GuiSlot.func_148138_e(GuiSlot.java:123)
	at net.minecraft.client.gui.GuiSlot.func_148135_f(GuiSlot.java:177)
	at net.minecraft.client.gui.GuiSlot.func_148121_k(GuiSlot.java:172)
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:694)
	at net.ccbluex.liquidbounce.ui.client.GuiScripts.func_73863_a(GuiScripts.kt:49)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)

-- Screen render details --
Details:
	Screen name: net.ccbluex.liquidbounce.ui.client.GuiScripts
	Mouse location: Scaled: (362, 160). Absolute: (725, 327)
	Screen size: Scaled: (720, 324). Absolute: (1440, 648). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1431)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-12
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2578318680 bytes (2458 MB) / 3022520320 bytes (2882 MB) up to 3022520320 bytes (2882 MB)
	JVM Flags: 3 total; -Xms3000M -Xmx3000M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (LiquidBounce-plus.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.patcher.tweaker.ClassTransformer
  net.ccbluex.liquidbounce.patcher.tweaker.other.ModClassTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	Launched Version: 1.8.9
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: vgpu 1.3.68 GL version 3.0, vgpu
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Fabric Mods
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.0
	OpenGlRenderer: vgpu 1.3.68
	OpenGlVendor: vgpu
	CpuCount: 8

```text
[Paste Here]
```

**System Information**
 - OS: [Android 12 Linux Arm64]
 - Minecraft Version: [1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [3.0.0]

**Other Installed Mods**
Optifine 1.8.9 Forge
- <Example Mod 1.0>

**Comment by SMAAMX** [comment]
LiquidBounce Plus no crashed
Sorry, for some reason I can not use my computer to play games😓🙏

**Comment by SMAAMX** [comment]
![Screenshot_۲۰۲۲-۰۳-۲۴-۲۳-۱۸-۳۵-۱۰۳_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/90418723/160113908-ce08e017-334f-4938-9037-983f4faa817c.jpg)

**Comment by SMAAMX** [comment]
https://user-images.githubusercontent.com/90418723/160114728-5541dec2-4ef6-4170-80c3-113503319c42.mp4
