### ISSUE TITLE
new FDP Client update crashes

### ISSUE THREAD

**Issue by THEKEMER** [UnlegitMC/FDPClient#1907]
Hi
I have new FDP Client crashes 
My crach Log
Help Pls
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-efcee50.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 27.03.22 11:07
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.vitox.Particle.fall(Particle.java:107)
	at net.vitox.ParticleGenerator.draw(ParticleGenerator.java:38)
	at net.ccbluex.liquidbounce.utils.render.ParticleUtils.drawParticles(ParticleUtils.java:15)
	at net.minecraft.client.gui.GuiScreen.handler$drawClientBackground$zbg000(GuiScreen.java:859)
	at net.minecraft.client.gui.GuiScreen.func_146278_c(GuiScreen.java)
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:605)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:593)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_73863_a(GuiLaunchOptionSelectMenu.kt:16)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1437)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.vitox.Particle.fall(Particle.java:107)
	at net.vitox.ParticleGenerator.draw(ParticleGenerator.java:38)
	at net.ccbluex.liquidbounce.utils.render.ParticleUtils.drawParticles(ParticleUtils.java:15)
	at net.minecraft.client.gui.GuiScreen.handler$drawClientBackground$zbg000(GuiScreen.java:859)
	at net.minecraft.client.gui.GuiScreen.func_146278_c(GuiScreen.java)
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:605)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:593)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_73863_a(GuiLaunchOptionSelectMenu.kt:16)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:537)

-- Screen render details --
Details:
	Screen name: net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu
	Mouse location: Scaled: (480, 270). Absolute: (960, 539)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1437)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 724276640 bytes (690 MB) / 1308622848 bytes (1248 MB) up to 3724541952 bytes (3552 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx3530M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_M5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-efcee50.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.80' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	Launched Version: ForgeOptiFine 1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.80, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: RainMoon.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 472.80
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by OrdinaryHacker** [comment]
This is the first time FDP crashed for me
