### ISSUE TITLE
My FDP Client is crashing after clicking on Legacy or Fancy UI

### ISSUE THREAD

**Issue by TheBest9121** [UnlegitMC/FDPClient#1947]
My FDP Client is crashing after click on Legacy or Fancy UI. First I opened FDP Client, It ran normally. Then I change the config, and the TLauncher account. Then I ran FDP Client and click Legacy UI. It closed. What's the problem to fix this. Shall it's TLauncher Issue or shall I uninstall the FDP Client and reinstall it back.

Here's the log text:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape1.8.9-1.4.jar)
  TransformerLoader (FDP Client.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 20/4/22 3:54 PM
Description: Updating screen events

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 49 column 11
	at com.google.gson.internal.Streams.parse(Streams.java:56)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.load(ConfigManager.kt:41)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.loadConfigSet(ConfigManager.kt:90)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:232)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_146284_a(GuiLaunchOptionSelectMenu.kt:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 49 column 11
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	at com.google.gson.internal.Streams.parse(Streams.java:44)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.gson.internal.Streams.parse(Streams.java:56)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.load(ConfigManager.kt:41)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.loadConfigSet(ConfigManager.kt:90)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:232)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_146284_a(GuiLaunchOptionSelectMenu.kt:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: net.ccbluex.liquidbounce.launch.data.fancyui.GuiPrepare
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 217099688 bytes (207 MB) / 503316480 bytes (480 MB) up to 4831838208 bytes (4608 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx4604M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_M5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	aiimprovements{0.0.1.20160401184835} [AI Improvements] (AIImprovements-1.8.9-0.0.1b20160401184840-universal.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-law-1.8.x.jar) 
	UCHIJA	no_fog{1.0.0} [NoFog] (NoFog-1.8.9b1.jar) 
	UCHIJA	texfix{4.0} [TextureFix] (TexFix V-1.8.9-4.0.jar) 
	UCHIJA	tlauncher_custom_cape_skin{1.4} [TLSkinCape] (tlskincape1.8.9-1.4.jar) 
	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape1.8.9-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
TransformerLoader (FDP Client.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA' Version: '4.6.0 - Build 27.20.100.9365' Renderer: 'NVIDIA GeForce RTX 3080'
	Launched Version: FDP Client
	LWJGL: 2.9.4
	OpenGL: NVIDIA  GeForce RTX 3080 NVIDIA
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: thebest9121's BedWars Pack 1.8.9.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-1005G1 CPU @ 3.30 Ghz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9365
	OpenGlRenderer: NVIDIA GeForce RTX 3080
	OpenGlVendor: NVIDIA
	CpuCount: 4

It's not a mod problem as I ran the same mods before, it ran well and after I changed account and config, it crashed when click Legacy or Fancy UI

**Comment by OlekAleksander** [comment]
dont use tlauncher

**Comment by TheBest9121** [comment]
> dont use tlauncher

I think that it's TLauncher Issue.
