### ISSUE TITLE
[Bug] Crash on Startup

### ISSUE THREAD

**Issue by ForBai** [UnlegitMC/FDPClient#1975]
**Describe the bug**
Minecraft crashes on startup

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PatcherTweaker (Patcher-1.8.1 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-beta.37064-for-MC-1.8.9.jar)
  Transformer (OringoClient-1.7.1-@everyone.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.3.jar)
  TransformerLoader (FDPClient-01fcb2f.jar)
  FMLLoadingPlugin (SkyblockClient-0.2.0-pre1.jar)
    (Pizza Client-1.1.3.jar)
  FMLLoadingPlugin (RoseGoldAddons-2.9.6.jar)
  AsmHelperLoadingPlugin (ctjs-2.0.4-1.8.9.jar)
  Skytils On Top (Skytils-1.2.5.jar)
  ModTweaker (Patcher-1.8.1 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 04.05.22 17:25
Description: Initializing game (unknown crash)

java.lang.ClassCastException: net.minecraft.client.Minecraft cannot be cast to gg.essential.mixins.ext.client.MinecraftExt
	at gg.essential.mixins.ext.client.MinecraftExtKt.getExt(MinecraftExt.kt:28)
	at gg.essential.util.ExtensionsKt.getExecutor(extensions.kt:130)
	at gg.essential.network.connectionmanager.Connection.<init>(Connection.java:67)
	at gg.essential.network.connectionmanager.ConnectionManager.<init>(ConnectionManager.java:47)
	at gg.essential.Essential.<init>(Essential.java:103)
	at gg.essential.Essential.getInstance(Essential.java:116)
	at net.minecraft.client.settings.GameSettings.handler$bnd000$registerEssentialKeyBindings(GameSettings.java:4878)
	at net.minecraft.client.settings.GameSettings.func_74300_a(GameSettings.java)
	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:341)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:395)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:121)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:67)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at gg.essential.mixins.ext.client.MinecraftExtKt.getExt(MinecraftExt.kt:28)
	at gg.essential.util.ExtensionsKt.getExecutor(extensions.kt:130)
	at gg.essential.network.connectionmanager.Connection.<init>(Connection.java:67)
	at gg.essential.network.connectionmanager.ConnectionManager.<init>(ConnectionManager.java:47)
	at gg.essential.Essential.<init>(Essential.java:103)
	at gg.essential.Essential.getInstance(Essential.java:116)
	at net.minecraft.client.settings.GameSettings.handler$bnd000$registerEssentialKeyBindings(GameSettings.java:4878)
	at net.minecraft.client.settings.GameSettings.func_74300_a(GameSettings.java)
	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:341)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:395)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:121)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:67)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ChatTriggers modules: [Module{name=soopyApis,version=0.1.12}, Module{name=RenderLib,version=0.4.0}, Module{name=axios,version=1.0.3}, Module{name=RichPresence,version=1.0.1}, Module{name=NotEnoughEnhancements,version=1.0}, Module{name=CustomTabCompletions,version=1.0.2}, Module{name=SettingsManager,version=1.2.2}, Module{name=SoopyV2UpdateButtonPatcher,version=0.0.2}, Module{name=Promise,version=1.1.0}, Module{name=Elementa,version=1.5.2}, Module{name=request,version=2.1.0}, Module{name=requestV2,version=2.0.1}, Module{name=PromiseV2,version=1.0.4}, Module{name=BeaconBeam,version=1.0.0}, Module{name=CustomRank,version=1.5}, Module{name=DungeonUtilities,version=0.9.9}, Module{name=CTAutocomplete-2.0.4,version=2.0.4}, Module{name=HoeUtilitiesV2,version=1.4.2}, Module{name=IllegalMap,version=3.2.2}, Module{name=SoopyV2,version=2.1.48}, Module{name=CTAutocomplete,version=2.0.2}, Module{name=guimanager,version=0.0.9}, Module{name=mappings,version=0.0.1}, Module{name=soopyAddonsData,version=0.0.1}, Module{name=PersistentData,version=1.1.3}, Module{name=DeepProxy,version=2.0.0}, Module{name=Vigilance,version=1.3.2}, Module{name=PogData,version=1.0.1}, Module{name=sleep,version=1.0.0}]
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.15.0-27-generic
	Java Version: 1.8.0_275, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 249854904 bytes (238 MB) / 536870912 bytes (512 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 7 total; -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
PatcherTweaker (Patcher-1.8.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-beta.37064-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
Transformer (OringoClient-1.7.1-@everyone.jar)
  me.oringo.oringoclient.OringoDevMode
ItemPatchingLoader (ItemPhysic Lite 1.3.jar)
  com.creativemd.itemphysic.ItemTransformer
TransformerLoader (FDPClient-01fcb2f.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
FMLLoadingPlugin (SkyblockClient-0.2.0-pre1.jar)
  
  (Pizza Client-1.1.3.jar)
  
FMLLoadingPlugin (RoseGoldAddons-2.9.6.jar)
  
AsmHelperLoadingPlugin (ctjs-2.0.4-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
Skytils On Top (Skytils-1.2.5.jar)
  skytils.skytilsmod.asm.SkytilsTransformer
ModTweaker (Patcher-1.8.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: ~~ERROR~~ NullPointerException: null
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0
```

**System Information**
 - OS: Linux Ubuntu 22.04
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: newest

**Comment by KohleBrot** [comment]
> i just found it out myself all good
what did you do to make it work
