### ISSUE TITLE
Error to launch

### ISSUE THREAD

**Issue by snowfox0518** [UnlegitMC/FDPClient#243]
i can't open my fdp client on my HMCL
翻译:老子fdp坏了，hmcl开不了
md之前用pcl2然后跟我说用hmcl
艹

**Comment by snowfox0518** [comment]
忘了把报错内容安排了
Command: "C:\\Program Files (x86)\\Java\\jdk1.8.0_73\\jre\\bin\\java.exe" "-Dminecraft.client.jar=D:\\HMCL\\FDP\\versions\\1.8.9-Forge 11.15.1.2318-OptiFine_M5\\1.8.9-Forge 11.15.1.2318-OptiFine_M5.jar" -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xss1m -Xmx1024m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump "-Djava.library.path=D:\\HMCL\\FDP\\versions\\1.8.9-Forge 11.15.1.2318-OptiFine_M5\\natives" -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.3.200 -cp "D:\\HMCL\\FDP\\libraries\\com\\mojang\\netty\\1.7.7\\netty-1.7.7.jar;D:\\HMCL\\FDP\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;D:\\HMCL\\FDP\\libraries\\net\\java\\dev\\jna\\jna\\3.4.0\\jna-3.4.0.jar;D:\\HMCL\\FDP\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;D:\\HMCL\\FDP\\libraries\\com\\ibm\\icu\\icu4j-core-mojang\\51.2\\icu4j-core-mojang-51.2.jar;D:\\HMCL\\FDP\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\4.6\\jopt-simple-4.6.jar;D:\\HMCL\\FDP\\libraries\\com\\paulscode\\codecjorbis\\20101023\\codecjorbis-20101023.jar;D:\\HMCL\\FDP\\libraries\\com\\paulscode\\codecwav\\20101023\\codecwav-20101023.jar;D:\\HMCL\\FDP\\libraries\\com\\paulscode\\libraryjavasound\\20101123\\libraryjavasound-20101123.jar;D:\\HMCL\\FDP\\libraries\\com\\paulscode\\librarylwjglopenal\\20100824\\librarylwjglopenal-20100824.jar;D:\\HMCL\\FDP\\libraries\\com\\paulscode\\soundsystem\\20120107\\soundsystem-20120107.jar;D:\\HMCL\\FDP\\libraries\\io\\netty\\netty-all\\4.0.23.Final\\netty-all-4.0.23.Final.jar;D:\\HMCL\\FDP\\libraries\\com\\google\\guava\\guava\\17.0\\guava-17.0.jar;D:\\HMCL\\FDP\\libraries\\org\\apache\\commons\\commons-lang3\\3.3.2\\commons-lang3-3.3.2.jar;D:\\HMCL\\FDP\\libraries\\commons-io\\commons-io\\2.4\\commons-io-2.4.jar;D:\\HMCL\\FDP\\libraries\\commons-codec\\commons-codec\\1.9\\commons-codec-1.9.jar;D:\\HMCL\\FDP\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;D:\\HMCL\\FDP\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;D:\\HMCL\\FDP\\libraries\\com\\google\\code\\gson\\gson\\2.2.4\\gson-2.2.4.jar;D:\\HMCL\\FDP\\libraries\\com\\mojang\\authlib\\1.5.21\\authlib-1.5.21.jar;D:\\HMCL\\FDP\\libraries\\com\\mojang\\realms\\1.7.59\\realms-1.7.59.jar;D:\\HMCL\\FDP\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;D:\\HMCL\\FDP\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;D:\\HMCL\\FDP\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;D:\\HMCL\\FDP\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;D:\\HMCL\\FDP\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.0-beta9\\log4j-api-2.0-beta9.jar;D:\\HMCL\\FDP\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.0-beta9\\log4j-core-2.0-beta9.jar;D:\\HMCL\\FDP\\libraries\\org\\lwjgl\\lwjgl\\lwjgl\\2.9.4-nightly-20150209\\lwjgl-2.9.4-nightly-20150209.jar;D:\\HMCL\\FDP\\libraries\\org\\lwjgl\\lwjgl\\lwjgl_util\\2.9.4-nightly-20150209\\lwjgl_util-2.9.4-nightly-20150209.jar;D:\\HMCL\\FDP\\libraries\\tv\\twitch\\twitch\\6.5\\twitch-6.5.jar;D:\\HMCL\\FDP\\libraries\\optifine\\OptiFine\\1.8.9_HD_U_M5\\OptiFine-1.8.9_HD_U_M5.jar;D:\\HMCL\\FDP\\libraries\\net\\minecraft\\launchwrapper\\1.12\\launchwrapper-1.12.jar;D:\\HMCL\\FDP\\libraries\\net\\minecraftforge\\forge\\1.8.9-11.15.1.2318-1.8.9\\forge-1.8.9-11.15.1.2318-1.8.9.jar;D:\\HMCL\\FDP\\libraries\\net\\minecraft\\launchwrapper\\1.12\\launchwrapper-1.12.jar;D:\\HMCL\\FDP\\libraries\\org\\ow2\\asm\\asm-all\\5.0.3\\asm-all-5.0.3.jar;D:\\HMCL\\FDP\\libraries\\jline\\jline\\2.13\\jline-2.13.jar;D:\\HMCL\\FDP\\libraries\\com\\typesafe\\akka\\akka-actor_2.11\\2.3.3\\akka-actor_2.11-2.3.3.jar;D:\\HMCL\\FDP\\libraries\\com\\typesafe\\config\\1.2.1\\config-1.2.1.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-actors-migration_2.11\\1.1.0\\scala-actors-migration_2.11-1.1.0.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-compiler\\2.11.1\\scala-compiler-2.11.1.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\plugins\\scala-continuations-library_2.11\\1.0.2\\scala-continuations-library_2.11-1.0.2.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\plugins\\scala-continuations-plugin_2.11.1\\1.0.2\\scala-continuations-plugin_2.11.1-1.0.2.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-library\\2.11.1\\scala-library-2.11.1.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-parser-combinators_2.11\\1.0.1\\scala-parser-combinators_2.11-1.0.1.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-reflect\\2.11.1\\scala-reflect-2.11.1.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-swing_2.11\\1.0.1\\scala-swing_2.11-1.0.1.jar;D:\\HMCL\\FDP\\libraries\\org\\scala-lang\\scala-xml_2.11\\1.0.2\\scala-xml_2.11-1.0.2.jar;D:\\HMCL\\FDP\\libraries\\lzma\\lzma\\0.0.1\\lzma-0.0.1.jar;D:\\HMCL\\FDP\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\4.6\\jopt-simple-4.6.jar;D:\\HMCL\\FDP\\libraries\\java3d\\vecmath\\1.5.2\\vecmath-1.5.2.jar;D:\\HMCL\\FDP\\libraries\\net\\sf\\trove4j\\trove4j\\3.0.3\\trove4j-3.0.3.jar;D:\\HMCL\\FDP\\versions\\1.8.9-Forge 11.15.1.2318-OptiFine_M5\\1.8.9-Forge 11.15.1.2318-OptiFine_M5.jar" net.minecraft.launchwrapper.Launch --tweakClass optifine.OptiFineForgeTweaker --username snowfox_0518 --version "HMCL 3.3.200" --gameDir D:\HMCL\FDP --assetsDir D:\HMCL\FDP\assets --assetIndex 1.8 --uuid a48b6c48db663539922b6efcd7ea1c4c --accessToken 754615046367488e8b56ebe285ca0795 --userProperties {} --userType mojang --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --width 854 --height 480
2021-09-04 12:45:59,576 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[12:45:59] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[12:45:59] [main/INFO]: Using primary tweak class name optifine.OptiFineForgeTweaker
[12:45:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:45:59] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
OptiFineForgeTweaker: acceptOptions
Error checking Forge server: java.lang.NullPointerException: null
OptiFineForgeTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: D:\HMCL\FDP\libraries\optifine\OptiFine\1.8.9_HD_U_M5\OptiFine-1.8.9_HD_U_M5.jar
[12:45:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[12:45:59] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[12:45:59] [main/INFO]: Java is Java HotSpot(TM) Client VM, version 1.8.0_73, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jdk1.8.0_73\jre
[12:45:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from FDPClient-v1.jar
[12:45:59] [main/WARN]: The coremod lain.mods.inputfix.InputFix does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:45:59] [main/INFO]: Loading tweaker com.spiderfrog.gadgets.main.OAMTweaker from OldAnimationsMod-Animations & Cosmetics_2.6.4-mc_Forge1.8.9.jar
[12:45:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:45:59] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[12:45:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.10 Source=file:/D:/HMCL/FDP/mods/FDPClient-v1.jar Service=LaunchWrapper Env=CLIENT
[12:45:59] [main/DEBUG]: Instantiating coremod class TransformerLoader
[12:45:59] [main/WARN]: The coremod net.ccbluex.liquidbounce.injection.forge.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:45:59] [main/DEBUG]: Enqueued coremod TransformerLoader
[12:45:59] [main/INFO]: Loading tweak class name com.spiderfrog.gadgets.main.OAMTweaker
[12:45:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:45:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:45:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:45:59] [main/INFO]: Calling tweak class com.spiderfrog.gadgets.main.OAMTweaker
[12:45:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:45:59] [main/DEBUG]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[12:45:59] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[12:46:00] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[12:46:00] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[12:46:00] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[12:46:00] [main/DEBUG]: Injection complete
[12:46:00] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin}
[12:46:00] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[12:46:01] [main/DEBUG]: Read 825 binary patches
[12:46:01] [main/DEBUG]: Loading deobfuscation resource /deobfuscation_data-1.8.9.lzma with 27891 records
[12:46:01] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:46:01] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[12:46:01] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[12:46:01] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:46:01] [main/DEBUG]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[12:46:01] [main/DEBUG]: Injection complete
[12:46:01] [main/DEBUG]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[12:46:01] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[12:46:01] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[12:46:01] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:46:01] [main/DEBUG]: Injecting coremod InputFix {lain.mods.inputfix.InputFix} class transformers
[12:46:01] [main/TRACE]: Registering transformer lain.mods.inputfix.InputFixTransformer
[12:46:01] [main/DEBUG]: Injection complete
[12:46:01] [main/DEBUG]: Running coremod plugin for InputFix {lain.mods.inputfix.InputFix}
[12:46:01] [main/DEBUG]: Running coremod plugin InputFix
[12:46:01] [main/DEBUG]: Coremod plugin class InputFix run successfully
[12:46:01] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:46:01] [main/DEBUG]: Injecting coremod ItemPatchingLoader {com.creativemd.itemphysic.ItemPatchingLoader} class transformers
[12:46:01] [main/TRACE]: Registering transformer com.creativemd.itemphysic.ItemTransformer
[12:46:01] [main/DEBUG]: Injection complete
[12:46:01] [main/DEBUG]: Running coremod plugin for ItemPatchingLoader {com.creativemd.itemphysic.ItemPatchingLoader}
[12:46:01] [main/DEBUG]: Running coremod plugin ItemPatchingLoader
[12:46:01] [main/DEBUG]: Coremod plugin class ItemPatchingLoader run successfully
[12:46:01] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[12:46:01] [main/INFO]: Compatibility level set to JAVA_8
[12:46:01] [main/ERROR]: Mixin config liquidbounce.forge.mixins.json does not specify "minVersion" property
2021-09-04 12:46:01,951 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-09-04 12:46:02,018 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[12:46:02] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@1fc3126
[12:46:02] [main/DEBUG]: Injecting coremod TransformerLoader {net.ccbluex.liquidbounce.injection.forge.TransformerLoader} class transformers
[12:46:02] [main/TRACE]: Registering transformer net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
[12:46:02] [main/TRACE]: Registering transformer net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
[12:46:02] [main/DEBUG]: Injection complete
[12:46:02] [main/DEBUG]: Running coremod plugin for TransformerLoader {net.ccbluex.liquidbounce.injection.forge.TransformerLoader}
[12:46:02] [main/DEBUG]: Running coremod plugin TransformerLoader
[12:46:02] [main/DEBUG]: Coremod plugin class TransformerLoader run successfully
[12:46:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:46:02] [main/DEBUG]: Loaded 165 rules from AccessTransformer config file forge_at.cfg
[12:46:02] [main/DEBUG]: Loaded 48 rules from AccessTransformer mod jar file D:\HMCL\FDP\mods\FDPClient-v1.jar!META-INF/liquidbounce_at.cfg

[12:46:02] [main/DEBUG]: Validating minecraft
[12:46:02] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:46:02] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[12:46:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:46:02] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[12:46:02] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[12:46:02] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchTarget
[12:46:02] [main/ERROR]: There is a binary discrepency between the expected input class net.minecraft.client.renderer.BlockModelRenderer (bgf) and the actual class. Checksum on disk is fb69c853, in patch 7fe69015. Things are probably about to go very wrong. Did you put something into the jar file?
[12:46:02] [main/ERROR]: FML is going to ignore this error, note that the patch will not be applied, and there is likely to be a malfunctioning behaviour, including not running at all
[12:46:02] [main/INFO]: Found Minecraft Class to inject
[12:46:02] [main/INFO]: Found Minecraft Start Method
[12:46:02] [main/INFO]: Tweak Gadgets init Method into Minecraft
[12:46:03] [main/INFO]: [ItemPhysic] Patching bjf
[12:46:03] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[12:46:03] [main/INFO]: Found Minecraft Class to inject
[12:46:03] [main/INFO]: Found Minecraft Start Method
[12:46:03] [main/INFO]: Tweak Gadgets init Method into Minecraft
[12:46:04] [Client thread/INFO]: Setting user: <player>
[12:46:04] [Client thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.createRegistry(PersistentRegistryManager.java:85) ~[PersistentRegistryManager$PersistentRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.access$000(PersistentRegistryManager.java:46) ~[PersistentRegistryManager$PersistentRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.createRegistry(PersistentRegistryManager.java:135) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:114) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:40) ~[GameData.class:?]
	at net.minecraft.block.Block.<clinit>(Block.java:41) ~[afh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:512) ~[kb.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:320) ~[ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.RegistryDelegate
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.createRegistry(PersistentRegistryManager.java:85) ~[PersistentRegistryManager$PersistentRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.access$000(PersistentRegistryManager.java:46) ~[PersistentRegistryManager$PersistentRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.createRegistry(PersistentRegistryManager.java:135) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:114) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:40) ~[GameData.class:?]
	at net.minecraft.block.Block.<clinit>(Block.java:41) ~[afh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:512) ~[kb.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:320) ~[ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.SecurityException: class "net.minecraftforge.fml.common.registry.RegistryDelegate"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895) ~[?:1.8.0_73]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665) ~[?:1.8.0_73]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758) ~[?:1.8.0_73]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.createRegistry(PersistentRegistryManager.java:85) ~[PersistentRegistryManager$PersistentRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.access$000(PersistentRegistryManager.java:46) ~[PersistentRegistryManager$PersistentRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.createRegistry(PersistentRegistryManager.java:135) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:114) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:40) ~[GameData.class:?]
	at net.minecraft.block.Block.<clinit>(Block.java:41) ~[afh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:512) ~[kb.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:320) ~[ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[12:46:04] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Exception in thread "Client thread"

**Comment by liulihaocai** [comment]
你mc有问题去重装
