### ISSUE TITLE
[suggestion] use httputils.download(url: String, file: File) instead of fileutils.downloadFile()

### ISSUE THREAD

**Issue by exit-scammed** [UnlegitMC/FDPClient#263]
this may help who knows, btw I'm also referring to one log that a person had sent me later on FDP discord 
since I saw many people asking for help with the same stacktrace and different jre1.8 update I decided to take a look in a random log

```log
Stacktrace:
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at net.ccbluex.liquidbounce.utils.FileUtils.downloadFile(FileUtils.kt:25)
	at net.ccbluex.liquidbounce.ui.ultralight.UltralightEngine.checkNativeResources(UltralightEngine.kt:94)
	at net.ccbluex.liquidbounce.ui.ultralight.UltralightEngine.initResources(UltralightEngine.kt:73)
	at net.ccbluex.liquidbounce.launch.options.UltralightLaunchOption.head(UltralightLaunchOption.kt:15)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:124)
	at net.minecraft.client.Minecraft.handler$startGame$zzf000(Minecraft.java:3205)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
```

ignoring all the `sun.*`, you can straightly see that the error occurred in FileUtils.downloadFile

p/s: using a normal browser I still can get the zip file but not in the client.

after browsing the repo for a while here's what you need to replace with the method from HttpUtils:
https://github.com/UnlegitMC/FDPClient/blob/master/src/main/java/net/ccbluex/liquidbounce/ui/ultralight/UltralightEngine.kt#L94

even if this doesn't help, you should really recheck the resource website's certificate again for sure

**Comment by liulihaocai** [comment]
thanks for ur help!
