### ISSUE TITLE
FDPClient crashing

### ISSUE THREAD

**Issue by ENDER1355** [UnlegitMC/FDPClient#314]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-v1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/17/21 3:11 PM
Description: Initializing game

SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabeled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
net.minecraftforge.fml.client.SplashProgress$5: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:516)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:571)
	... 10 more
Caused by: java.lang.NullPointerException
	at net.minecraft.client.gui.FontRenderer.handler$drawString$zbm000(FontRenderer.java:974)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270)
	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414)
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 772694400 bytes (736 MB) / 1435500544 bytes (1369 MB) up to 3810525184 bytes (3634 MB)
	JVM Flags: 2 total; -Xverify:none -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-v1.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14760 Compatibility Profile Context 20.45.37.01 27.20.14537.1001' Renderer: 'AMD Radeon (TM) R9 380 Series'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 380 Series GL version 4.6.14760 Compatibility Profile Context 20.45.37.01 27.20.14537.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz

**Comment by ENDER1355** [comment]
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
> TransformerLoader (FDPClient-v1.jar)
> Contact their authors BEFORE contacting forge
> 
> // My bad.
> 
> Time: 9/17/21 3:11 PM
> Description: Initializing game
> 
> SplashProgress has detected a error loading Minecraft.
> This can sometimes be caused by bad video drivers.
> We have automatically disabeled the new Splash Screen in config/splash.properties.
> Try reloading minecraft before reporting any errors.
> net.minecraftforge.fml.client.SplashProgress$5: java.lang.IllegalStateException: Splash thread
> at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
> at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
> at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
> at net.minecraft.client.main.Main.main(SourceFile:124)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.IllegalStateException: Splash thread
> at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:516)
> at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:571)
> ... 10 more
> Caused by: java.lang.NullPointerException
> at net.minecraft.client.gui.FontRenderer.handler$drawString$zbm000(FontRenderer.java:974)
> at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java)
> at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270)
> at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414)
> at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327)
> at java.lang.Thread.run(Unknown Source)
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head --
> Stacktrace:
> at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
> at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
> at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
> 
> -- Initialization --
> Details:
> Stacktrace:
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
> at net.minecraft.client.main.Main.main(SourceFile:124)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> Minecraft Version: 1.8.9
> Operating System: Windows 10 (amd64) version 10.0
> Java Version: 1.8.0_291, Oracle Corporation
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 772694400 bytes (736 MB) / 1435500544 bytes (1369 MB) up to 3810525184 bytes (3634 MB)
> JVM Flags: 2 total; -Xverify:none -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
> States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> UCHIJA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
> UCHIJA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar)
> UCHIJA Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar)
> Loaded coremods (and transformers):
> TransformerLoader (FDPClient-v1.jar)
> net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
> net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
> GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14760 Compatibility Profile Context 20.45.37.01 27.20.14537.1001' Renderer: 'AMD Radeon (TM) R9 380 Series'
> Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
> LWJGL: 2.9.4
> OpenGL: AMD Radeon (TM) R9 380 Series GL version 4.6.14760 Compatibility Profile Context 20.45.37.01 27.20.14537.1001, ATI Technologies Inc.
> GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> ```
> Using VBOs: No
> Is Modded: Definitely; Client brand changed to 'fml,forge'
> Type: Client (map_client.txt)
> Resource Packs: 
> Current Language: English (US)
> Profiler Position: N/A (disabled)
> CPU: 4x Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz
> ```

Or nvm it was due to legacy UI, i used it and now it works again
