### ISSUE TITLE
Crashed when initializing game

### ISSUE THREAD

**Issue by WindLeaf233** [UnlegitMC/FDPClient#433]
Crash report here:

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-2.0.0.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 21-10-5 ����3:00
Description: Initializing game

java.lang.IllegalStateException: From thread Thread[Client thread,10,main]: Thread[Thread-7,10,] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzf000(Minecraft.java:3177)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzf000(Minecraft.java:3177)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 112225456 bytes (107 MB) / 528482304 bytes (504 MB) up to 3758096384 bytes (3584 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx3584m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre1 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-2.0.0.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7870' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.8.9-Forge 11.15.1.2318-OptiFine_M6_pre1
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7870, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: �������� (�й�)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M6_pre1
	OptiFine Build: 20210326-211438
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7870
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4
```

**Comment by XYZmc2008** [comment]
me too

**Comment by WindLeaf233** [comment]
Is the video driver causing this crash? Or it seems that related with OpenGL.

**Comment by WindLeaf233** [comment]
Oh, I found the solution to this problem.

![image](https://user-images.githubusercontent.com/58383985/136019364-71c7c412-ac12-4b5b-ac0e-14ac1c8417d4.png)

Seems that the dev of this mod removed the automatic disabling of the loading screen? I remember that the game crashed the first time I used it, but the crash log told me something was automatically disabled, and then I started the game and it was normally launched.

## Solution
Same to the picture:
Disable the loading screen in the file **.minecraft/config/splash.properties**

I tried this and it succeeded, **Hope it's helpful to you all**

**Comment by WindLeaf233** [comment]
我尝试了一下将 splash.properties 的 enabled 改成 true，启动游戏，果不其然崩溃了
这证明了一个问题，就是这个导致的崩溃，只需要改成 false 就能解决这个问题

**Comment by WindLeaf233** [comment]
希望开发者可以添加一个检测，自动将 `splash.properties` 中的 loading screen 禁用，这样就不会出现 loading screen 导致的崩溃的问题

**Comment by WindLeaf233** [comment]
正确的解决办法是：找到 .minecraft/config/splash.properties，将其中的 enabled 的 true 改成 false，重启游戏
