### ISSUE TITLE
Broken Gui + Font Graphics

### ISSUE THREAD

**Issue by scorchhy** [UnlegitMC/FDPClient#609]
When using FDP Client on Forge, all the fonts and menus are bugged and aren't displayed properly.

Unfortunately, to reproduce this, i have no idea how, whenever i launch the 2.0.0 jar or any of the beta versions by having them in my mods folder, this is just how it displays in the Legacy UI, and just outright crashes when selecting the HTML UI

Screenshots: https://imgur.com/a/X3rHyVd

HTML UI Crash: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-0aeae197a0f23450f7abfd2074669399eda523c1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 31/10/21 23:42
Description: Updating screen events

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.download(HttpUtils.kt:82)
	at net.ccbluex.liquidbounce.ui.ultralight.UltralightEngine.checkNativeResources(UltralightEngine.kt:96)
	at net.ccbluex.liquidbounce.ui.ultralight.UltralightEngine.initResources(UltralightEngine.kt:73)
	at net.ccbluex.liquidbounce.launch.options.UltralightLaunchOption.start(UltralightLaunchOption.kt:15)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:184)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_146284_a(GuiLaunchOptionSelectMenu.kt:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:467)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 36 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.download(HttpUtils.kt:82)
	at net.ccbluex.liquidbounce.ui.ultralight.UltralightEngine.checkNativeResources(UltralightEngine.kt:96)
	at net.ccbluex.liquidbounce.ui.ultralight.UltralightEngine.initResources(UltralightEngine.kt:73)
	at net.ccbluex.liquidbounce.launch.options.UltralightLaunchOption.start(UltralightLaunchOption.kt:15)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:184)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_146284_a(GuiLaunchOptionSelectMenu.kt:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:467)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)

-- Affected screen --
Details:
	Screen name: net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 362924232 bytes (346 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-0aeae197a0f23450f7abfd2074669399eda523c1.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4963, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !     §3defrosted §8[§f16x§8].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460T CPU @ 1.90GHz
	
	
	
 - Windows 10
 - Minecraft 1.8.9
 - Forge 11.15.1.2318
 - FDPClient Version 2.0.0

No other mods.

I also have tried reinstalling the FDP folder and messing around with fonts, but both do not work

**Comment by exit-scammed** [comment]
both are liuli's fault, but for the HTML GUI you will probably need to manually download on windows, I don't know why.

**Comment by scorchhy** [comment]
any method known rn to fix it?

**Comment by contionability** [comment]
Liuli is using Linux instead of Windows so...
but Legacy and HTML UI work perfectly on my PC(Both Windows and Linux work well)
i think the problems may mainly caused by mem usage or GPU
