### ISSUE TITLE
[Bug] 打不开游戏（cant open game

### ISSUE THREAD

**Issue by llt12213** [UnlegitMC/FDPClient#626]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
i clicked the launch game then sutck at a black windows with fdp's title
launcher:PCL2

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
[21:29:20] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from FDPClient-2.0.0.jar
[21:29:20] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:29:20] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:29:20] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/D:/Minecraft/.minecraft/versions/1.8.9-FDP/mods/FDPClient-2.0.0.jar Service=LaunchWrapper Env=CLIENT
[21:29:21] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[21:29:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:29:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:29:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:29:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:29:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:29:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:29:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:29:25] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
2021-11-10 21:29:25,726 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-11-10 21:29:25,817 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-11-10 21:29:25,828 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[21:29:25] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@c9413d8
[21:29:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:29:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:29:27] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:29:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:29:27] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:29:31] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:29:35] [Client thread/INFO]: Setting user: Dr_Li
[21:29:43] [Client thread/INFO]: LWJGL Version: 2.9.4
[21:29:51] [Client thread/WARN] [FML]: =============================================================
[21:29:51] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[21:29:51] [Client thread/WARN] [FML]: Offendor: com/sun/jna/Native.main([Ljava/lang/String;)V
[21:29:51] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[21:29:51] [Client thread/WARN] [FML]: =============================================================
[21:29:54] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-2.0.0.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 21-11-10 下午9:29
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 50859656 bytes (48 MB) / 382730240 bytes (365 MB) up to 1503657984 bytes (1434 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx1433m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-2.0.0.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 510.06' Renderer: 'NVIDIA GeForce 930M/PCIe/SSE2'
[21:29:55] [Client thread/INFO] [FML]: MinecraftForge v11.15.1.2318 Initialized
[21:29:55] [Client thread/INFO] [FML]: Replaced 229 ore recipies
[21:29:56] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[21:29:56] [Client thread/INFO] [FML]: Searching D:\Minecraft\.minecraft\versions\1.8.9-FDP\mods for mods
[21:29:57] [Thread-7/ERROR] [FML]: Splash thread Exception
java.lang.NullPointerException
	at net.minecraft.client.gui.FontRenderer.handler$drawString$zbm000(FontRenderer.java:974) ~[avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java) ~[avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270) ~[avn.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414) ~[SplashProgress$3.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327) ~[SplashProgress$3.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[21:30:02] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[21:30:03] [Client thread/INFO] [FML]: FML has found a non-mod file FDPClient-2.0.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[21:30:03] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[21:30:03] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[21:30:04] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[21:30:04] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[21:30:04] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[21:30:04] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[21:30:04] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[21:30:04] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[21:30:04] [Client thread/INFO] [FML]: Applying holder lookups
[21:30:04] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[21:30:04] [Client thread/INFO] [FML]: Holder lookups applied
[21:30:04] [Client thread/INFO] [FML]: Injecting itemstacks
[21:30:04] [Client thread/INFO] [FML]: Itemstack injection complete
[21:30:05] [Sound Library Loader/INFO]: Starting up SoundSystem...
[21:30:05] [Thread-8/INFO]: Initializing LWJGL OpenAL
[21:30:05] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:30:06] [Thread-8/INFO]: OpenAL initialized.
[21:30:06] [Sound Library Loader/INFO]: Sound engine started
[21:30:15] [Client thread/INFO] [FML]: Max texture size: 16384
[21:30:15] [Client thread/INFO]: Created: 16x16 textures-atlas
[21:30:18] [Client thread/INFO] [FML]: Injecting itemstacks
[21:30:18] [Client thread/INFO] [FML]: Itemstack injection complete
[21:30:18] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 3 mods
[21:30:18] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[21:30:19] [Client thread/INFO]: SoundSystem shutting down...
[21:30:19] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[21:30:19] [Sound Library Loader/INFO]: Starting up SoundSystem...
[21:30:19] [Thread-10/INFO]: Initializing LWJGL OpenAL
[21:30:19] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:30:19] [Thread-10/INFO]: OpenAL initialized.
[21:30:19] [Sound Library Loader/INFO]: Sound engine started
[21:30:21] [Client thread/INFO] [FML]: Max texture size: 16384
[21:30:22] [Client thread/INFO]: Created: 512x512 textures-atlas
[21:30:23] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-2.0.0.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 21-11-10 下午9:30
Description: Initializing game

java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-7,5,] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzf000(Minecraft.java:3179)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzf000(Minecraft.java:3179)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177058960 bytes (168 MB) / 498073600 bytes (475 MB) up to 1503657984 bytes (1434 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx1433m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-2.0.0.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 510.06' Renderer: 'NVIDIA GeForce 930M/PCIe/SSE2'
	Launched Version: 1.8.9-FDP
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce 930M/PCIe/SSE2 GL version 4.6.0 NVIDIA 510.06, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)(chinese
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
[21:30:23] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# D:\Minecraft\.minecraft\versions\1.8.9-FDP\crash-reports\crash-2021-11-10_21.30.23-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**System Information**
 - OS: [e.g. Windows 11]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- optifine M5

**Additional info**

**Comment by zWTbz** [comment]
are u using pcl launcher?

**Comment by llt12213** [comment]
> are u using pcl launcher?

对
严格说是PCL2
Yes
strictly speaking is PCL2

**Comment by zWTbz** [comment]
> > are u using pcl launcher?
> 
> 对 严格说是PCL2 Yes strictly speaking is PCL2

 fdp doesnt support pcl launcher

**Comment by llt12213** [comment]
> > > 你在使用 pcl 启动器吗？
> > 
> > 
> > 对 严格说是PCL2 是的严格说是PCL2
> 
> fdp 不支持 pcl 启动器

但是我用其他启动器比如HCML也这样啊

**Comment by WindLeaf233** [comment]
see #433
