### ISSUE TITLE
crashing[Bug]

### ISSUE THREAD

**Issue by lolidk333** [UnlegitMC/FDPClient#637]
keeps crashing after i click one of the uis(dont matter if html or legacy)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-2.0.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 21.11.21 01:10
Description: Updating screen events

java.lang.NumberFormatException: For input string: "true"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at com.google.gson.JsonPrimitive.getAsFloat(JsonPrimitive.java:227)
	at net.ccbluex.liquidbounce.value.FloatValue.fromJson(FloatValue.kt:19)
	at net.ccbluex.liquidbounce.file.config.sections.ModulesSection.load(ModulesSection.kt:50)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.load(ConfigManager.kt:47)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.loadConfigSet(ConfigManager.kt:90)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:188)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_146284_a(GuiLaunchOptionSelectMenu.kt:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:467)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at com.google.gson.JsonPrimitive.getAsFloat(JsonPrimitive.java:227)
	at net.ccbluex.liquidbounce.value.FloatValue.fromJson(FloatValue.kt:19)
	at net.ccbluex.liquidbounce.file.config.sections.ModulesSection.load(ModulesSection.kt:50)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.load(ConfigManager.kt:47)
	at net.ccbluex.liquidbounce.file.config.ConfigManager.loadConfigSet(ConfigManager.kt:90)
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:188)
	at net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu.func_146284_a(GuiLaunchOptionSelectMenu.kt:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:467)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)

-- Affected screen --
Details:
	Screen name: net.ccbluex.liquidbounce.launch.data.GuiLaunchOptionSelectMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 151705512 bytes (144 MB) / 603979776 bytes (576 MB) up to 7348420608 bytes (7008 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx7000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_M5 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-2.0.0.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.8280, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Australian English (Australia)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8280
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 8]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318](idk where i can find)
 - FDPClient Version: [e.g. 2.0-PRE2]

**mods**
If you have any other mods installed, please list them here along with their version number.
- optifine_1.8.9_hd_u_m5

**Comment by llama-for3ver** [comment]
same

**Comment by ll11l1lIllIl1lll** [comment]
remove .minecraft/FDPClient-1.8/*

**Comment by llama-for3ver** [comment]
> remove .minecraft/FDPClient-1.8/*

So you delete the FDP folder?

**Comment by zezayne** [comment]
If your game crashed when you press the opinion for the ui , then put -Dfdp-legacy-ui on ur Jvm Arguements

**Comment by zezayne** [comment]
I think putting -noverify on ur Jvm Arguements will crash the client
